### ISSUE TITLE
Remove default author

### ISSUE THREAD

**Issue by ciroreed** [alexjoverm/typescript-library-starter#1]
![image](https://cloud.githubusercontent.com/assets/6052309/23106447/f9dd399a-f6ed-11e6-9fe5-0895bf01e3a3.png)

should be replaced by git credentials.. 

maybe install script by it self can retrieve git user from bash through this way: 
``` git config user.email ```
``` git config user.name ```

**Comment by alexjoverm** [comment]
Good point. Didn't figure this out since I haven't try it out of my git. 

It should be a matter of having those files as "template files", with some kind of strings patterns (like `--libraryname` in `package.json`, and replace them, first trying from `git config user.email|user.name` and if doesn't exists, by prompt. `Readme.md` wouldn't be a problem, since the user must rewrite it anyway.

PR welcome, otherwise I'll try to fix it as soon as possible :)

**Comment by alexjoverm** [comment]
@ciroreed Seems easy to get that info with https://www.npmjs.com/package/git-config
