### ISSUE TITLE
semantic release

### ISSUE THREAD

**Issue by lifeiscontent** [alexjoverm/typescript-library-starter#111]
Hey there!

I was wondering how I can fix my semantic release with this project?

you can see the build status here: https://travis-ci.org/lifeiscontent/backoff2

I'm only learning about semantic release from this project, any help would be appreciated. Thanks!

**Comment by alexjoverm** [comment]
Hey @lifeiscontent,

Try to do the first release manually yourself, then it should get back up. I remember @k1r0s had a similar issue.

Please, keep in mind I don't usually check issues like this, since is not an issue of this repo but your project. Consider for future issues using stackoverflow or semanic release repo.
