### ISSUE TITLE
Creating libraries containing multiple components

### ISSUE THREAD

**Issue by pulse00** [alexjoverm/typescript-library-starter#134]
Thanks for this starter - looks like a great place to get going. I have one question though.

We're planning an internal library with a large set of components. Is there a way we can create a module structure that allows importing like this:

```javascript
import { someMethod } from 'custom-lib/SomeModule';
```

I understand it can be used to build [multiple typescript classes](https://github.com/alexjoverm/typescript-library-starter/issues/83), but the answer in this issue assumes that each typescript file exports a single type.

If a file exports multiple types or methoes, the syntax for importing above will currently not work.
Is this possible somehow?

**Comment by alexjoverm** [comment]
Hi @pulse00!

Currently, this library is a one-package lib starter. Multiple packages would be a great feature, just like Babel, or Lodash do. We could use [Lerna](https://lernajs.io/) to do that, or some custom scripts.

Although, the users of this starter shouldn't be forced to use multiple packages.

Some suggestions:
 - Just document on the Readme.md the steps to integrate Lerna into this starter
 - If we ever do what @gimenete suggested on #135 about adding some options, this could be one of them.

I'd say go for option 1, since option 2 needs work and refinement.

I'd be happy to guide and work with anyone that wants to open a PR :)

**Comment by Glinkis** [comment]
Have a look at how Ant Design does it: https://github.com/ant-design/ant-design
Though they seem to use webpack for this.

**Comment by alexjoverm** [comment]
Sorry, I misunderstood this issue. I thought we were talking about multi-package approach, but I see we're talking at just having separate files/modules to be imported.

For that case, what @Glinkis exactly shared on https://github.com/Glinkis/jslib is a great approach. Basically it'd be about, aside from providing a bundled version as it is now, provide as well a transpiled but not bundled version of the code and place it in some folder inside dist, for example `dist/es` so it could be imported as `import { Whatever } from 'yourlib/es/whatever'`

PR are very welcome, otherwise I'll try to take a look when I find some time.

**Comment by Glinkis** [comment]
I'll have a look at implementing this as soon as I get some time.

I'll just output commonjs and es2015 modules into `dist/lib` and `dist/es`, and then point rollup to build from the `dist/es` instead of `compiled`.
Should we also include sourcemaps for these?

**Comment by alexjoverm** [comment]
Cool! Yes please, since sourcemaps are needed in the 2 steps-build they should be kept
