### ISSUE TITLE
issues with types

### ISSUE THREAD

**Issue by lifeiscontent** [alexjoverm/typescript-library-starter#145]
hey @alexjoverm , sorry to bug you.

I'm wondering why when green keeper updates packages it causes errors.

https://travis-ci.org/lifeiscontent/react-mutate-icon/builds/313184668

looks like it has to do with the build command from typescript-library-starter: `tsc && rollup -c rollup.config.ts && rimraf compiled && typedoc --out dist/docs --target es6 --theme minimal src`

**Comment by peterblazejewicz** [comment]
is this still relevant as there are passing builds? 
https://travis-ci.org/lifeiscontent/react-mutate-icon

**Comment by lifeiscontent** [comment]
@peterblazejewicz yeah, this is specific to green keeper.

**Comment by alexjoverm** [comment]
@lifeiscontent greenkeeper updates dependencies for you automatically. That's the expected behaviour, you don't wanna have your code broken because a dep upgrade, so it's failing early.

In your case, it looks like `@types/react` has been changed, causing your code to break as I see lots of type errors. 

That's something you must solve for that version. Please keep in mind that issue has nothing to do with this repo, so I'd suggest to refer to those tools docs and repos in these cases.

**Comment by lifeiscontent** [comment]
@alexjoverm ah, I didn’t realize that was a type conflict, thanks.
