### ISSUE TITLE
Add .rpt2_cache to gitignore or configure to tmp directory

### ISSUE THREAD

**Issue by mattmazzola** [alexjoverm/typescript-library-starter#173]
I've used this starter library in the past and don't remember this cache folder appearing.

Perhaps there was an update to the `rollup-plugin-typescript2` which starts to put cache in working directory instead of temp directory. See relate issue:
https://github.com/ezolenko/rollup-plugin-typescript2/issues/34

An easy fix would be to add .rpt2_cache to the .gitignore; but better solution might be to configure the plugin to put cache somewhere that is already ignored be convention.

**Comment by alexjoverm** [comment]
Thanks for reporting this and the investigation @mattmazzola!

Let's see the options we have. I would discard moving it out to a kind of `/tmp` folder, since that depends on the O.S.. Then we don't have any particular ignored folder for caches. We have the `compiled` and `build` folders, but not sure if that's the best place to put it since it could interfiere and collide with the actual behaviour.

Then I'd suggest to just ignore it. Do you agree or have a better idea?

**Comment by mattmazzola** [comment]
Yea, I agree that adding it to gitignore is simplest solution as well.  I am not very familiar with rollup plugins so I wanted to leave it open to suggestions.  I thought maybe there was some convention where all output from them should go in rollup folder.

In any case this is easy one to change again later if someone decides better, but will be good start.

**Comment by mattmazzola** [comment]
See #175
