### ISSUE TITLE
Change default tslint formatter to codeFrame

### ISSUE THREAD

**Issue by mattmazzola** [alexjoverm/typescript-library-starter#28]
Proposing to change the default formatter for tslint to codeFrame since it offers more helpful information to the developer. It will include sample code and the rules which was violated.

Example default (prose):
```
test/index.test.ts[7, 3]: file should end with a newline
```
Example (codeFrame):
```
test/index.test.ts
file should end with a newline (eofline)
  5 |     expect(add(1, 2)).toBe(3)
  6 |   })
> 7 | })
    |  ^
```

**Comment by alexjoverm** [comment]
Hi @mattmazzola, thanks for this issue.

Not sure if this would add value. Normally devs use the linter within the code editor, such as Atom, VSCode, Sublime... Where it marks already the lines of the errors. Thus I'd rather prefer the concise version of the message, since the `npm run lint` command is merely to validate the build.

I'll give it a try anyway and come back here.

**Comment by alexjoverm** [comment]
I've just realized that this command has nothing to do with the editors plugins, which they run eslint themselves.

Thanks! Good job!
