### ISSUE TITLE
Files should be removed as part of init

### ISSUE THREAD

**Issue by SteveALee** [alexjoverm/typescript-library-starter#43]
The following files do not make sense after init has been run as the files are then user's personal project, nothing to do with this starter (though maybe leave a 'poweredby' file?)

* tools/init.js - is it even safe to run it twice?
* .all-contributorsrc
* LICENCE - though users should be encouraged to chose one, may link to git hubs chooser?
* yarn.lock

**Comment by alexjoverm** [comment]
Hi!

Agree with the `tools/init.js`. Is not even safe to run it twice! I'd be fine if you can send a PR removing this, I'll take a look in a future otherwise, since this is low-prio.

Then: 

 - `yarn.lock`: lot of sense to keep it
 - `LICENSE`: I'd better keep it, the user can change it if they want. That encourages to use it.
 - `all-contributorsrc`: probably not, but the user can remove it.

Keep in mind the user has to adapt this starter to their needs (rewrite README.md, etc). The purpose of this starter is to spin up creating your library setup.

**Comment by SteveALee** [comment]
PR, coming up.

* yarn.lock - yes it might need updating for removed modules rather than deleting.
