### ISSUE TITLE
Feature Request: Validate commit message

### ISSUE THREAD

**Issue by foreggs** [alexjoverm/typescript-library-starter#67]
Would you consider using [validate-commit-msg](https://www.npmjs.com/package/validate-commit-msg) for validating commit messages? It is a good practice.

**Comment by alexjoverm** [comment]
It's used and configured, check out package.json config.

It's just disabled by default, but if you wanna enable it you must run `npm run semantic-release-prepare`. That will setup the commit-msg and prepush hooks, since semantic release need a strict commit style (although you don't need to use semantic release, so you can use it only for the hooks)
